name: Sync Missions

on:
  push:
    branches: [3.2_main]

env:
  FIREBASE_ADMIN_SA_JSON: ${{secrets.FIREBASE_ADMIN_SA_JSON}}
  FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
  FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}

jobs:
  sync-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run sync:missions
